apiVersion: v1
kind: Service
metadata:
  name: ajaydabeconsultancy-website
spec:
  selector:
    app: ajaydabeconsultancy-website
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 82
